services:
  postgres:
    image: postgres:16
    container_name: biblioteca_postgres
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - biblioteca_pgdata:/var/lib/postgresql/data

volumes:
  biblioteca_pgdata:

